package com.landmark.media.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.landmark.media.db.table.AlbumVo;
import com.landmark.media.db.table.AudioVo;
import com.landmark.media.db.table.FolderVo;
import com.landmark.media.db.table.GenreVo;
import com.landmark.media.db.table.RecordVo;
import com.landmark.media.db.table.SingerVo;
import com.landmark.media.db.table.VideoVo;

import com.landmark.media.db.dao.AlbumVoDao;
import com.landmark.media.db.dao.AudioVoDao;
import com.landmark.media.db.dao.FolderVoDao;
import com.landmark.media.db.dao.GenreVoDao;
import com.landmark.media.db.dao.RecordVoDao;
import com.landmark.media.db.dao.SingerVoDao;
import com.landmark.media.db.dao.VideoVoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig albumVoDaoConfig;
    private final DaoConfig audioVoDaoConfig;
    private final DaoConfig folderVoDaoConfig;
    private final DaoConfig genreVoDaoConfig;
    private final DaoConfig recordVoDaoConfig;
    private final DaoConfig singerVoDaoConfig;
    private final DaoConfig videoVoDaoConfig;

    private final AlbumVoDao albumVoDao;
    private final AudioVoDao audioVoDao;
    private final FolderVoDao folderVoDao;
    private final GenreVoDao genreVoDao;
    private final RecordVoDao recordVoDao;
    private final SingerVoDao singerVoDao;
    private final VideoVoDao videoVoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        albumVoDaoConfig = daoConfigMap.get(AlbumVoDao.class).clone();
        albumVoDaoConfig.initIdentityScope(type);

        audioVoDaoConfig = daoConfigMap.get(AudioVoDao.class).clone();
        audioVoDaoConfig.initIdentityScope(type);

        folderVoDaoConfig = daoConfigMap.get(FolderVoDao.class).clone();
        folderVoDaoConfig.initIdentityScope(type);

        genreVoDaoConfig = daoConfigMap.get(GenreVoDao.class).clone();
        genreVoDaoConfig.initIdentityScope(type);

        recordVoDaoConfig = daoConfigMap.get(RecordVoDao.class).clone();
        recordVoDaoConfig.initIdentityScope(type);

        singerVoDaoConfig = daoConfigMap.get(SingerVoDao.class).clone();
        singerVoDaoConfig.initIdentityScope(type);

        videoVoDaoConfig = daoConfigMap.get(VideoVoDao.class).clone();
        videoVoDaoConfig.initIdentityScope(type);

        albumVoDao = new AlbumVoDao(albumVoDaoConfig, this);
        audioVoDao = new AudioVoDao(audioVoDaoConfig, this);
        folderVoDao = new FolderVoDao(folderVoDaoConfig, this);
        genreVoDao = new GenreVoDao(genreVoDaoConfig, this);
        recordVoDao = new RecordVoDao(recordVoDaoConfig, this);
        singerVoDao = new SingerVoDao(singerVoDaoConfig, this);
        videoVoDao = new VideoVoDao(videoVoDaoConfig, this);

        registerDao(AlbumVo.class, albumVoDao);
        registerDao(AudioVo.class, audioVoDao);
        registerDao(FolderVo.class, folderVoDao);
        registerDao(GenreVo.class, genreVoDao);
        registerDao(RecordVo.class, recordVoDao);
        registerDao(SingerVo.class, singerVoDao);
        registerDao(VideoVo.class, videoVoDao);
    }
    
    public void clear() {
        albumVoDaoConfig.clearIdentityScope();
        audioVoDaoConfig.clearIdentityScope();
        folderVoDaoConfig.clearIdentityScope();
        genreVoDaoConfig.clearIdentityScope();
        recordVoDaoConfig.clearIdentityScope();
        singerVoDaoConfig.clearIdentityScope();
        videoVoDaoConfig.clearIdentityScope();
    }

    public AlbumVoDao getAlbumVoDao() {
        return albumVoDao;
    }

    public AudioVoDao getAudioVoDao() {
        return audioVoDao;
    }

    public FolderVoDao getFolderVoDao() {
        return folderVoDao;
    }

    public GenreVoDao getGenreVoDao() {
        return genreVoDao;
    }

    public RecordVoDao getRecordVoDao() {
        return recordVoDao;
    }

    public SingerVoDao getSingerVoDao() {
        return singerVoDao;
    }

    public VideoVoDao getVideoVoDao() {
        return videoVoDao;
    }

}
